---
- name: Install NTPd
  apt:
    name: ntp
    state: latest
  tags: ntp

# return code 0 means it's running
# return code 1 means it's not in the output of grep
# other return code is unknown
- name: Check if NTP is already in the vrf
  shell: "vrf task list | grep ntpd"
  register: ntp_vrf
  failed_when: ntp_vrf.rc >= 2
  when: nodes[ansible_hostname]["interfaces"]["mgmt"]["eth0"]["vrf"] != ""
  tags: ntp

- name: Configure NTP in management VRF
  command: "{{item}}"
  with_items:
    - systemctl stop ntp.service
    - systemctl disable ntp.service
    - systemctl start ntp@mgmt
  when: nodes[ansible_hostname]["interfaces"]["mgmt"]["eth0"]["vrf"] != "" and ntp_vrf.rc != 0
  tags: ntp
