---
- hosts: leafs
  become: yes
  roles:
    - ifupdown2-l2
    - ntp
    - netq
    - stp

- hosts: spines
  become: yes
  roles:
    - ifupdown2-l2
    - ntp
    - netq
    - stp

- hosts: servers
  become: yes
  roles:
    - ifupdown-l2
    - ntp
    - netq
    - ping

- hosts: leaf01
  become: yes
  tasks:
    - command: ebtables -I INPUT 1 -d BGA -i swp51 -j DROP

- hosts: spine01
  become: yes
  tasks:
    - command: ebtables -I INPUT 1 -d BGA -i swp1 -j DROP