---
- hosts: leafs
  become: yes
  roles:
    - ifupdown2-l2
    - ntp
    - netq

- hosts: spines
  become: yes
  roles:
    - ifupdown2-l2
    - ntp
    - netq


- hosts: servers
  become: yes
  roles:
    - ifupdown-l2
    - ntp
    - netq
    - ping
