---
- name: Install bridge utilities
  apt:
    name: bridge-utils
    state: latest
    update_cache: no
  tags: interfaces
  
# This configures the interfaces and sets the default internal route to point
# to the leafs. If the configuration changes, ifupdown will be reloaded.
- name: configure /etc/network/interfaces on the host (using legacy ifupdown)
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reload legacy networking
  tags: interfaces