---
- name: Add Cumulus Apt Key
  apt_key:
    url: "https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add Cumulus Repo for Ubuntu Xenial
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb xenial netq-1.2
    state: present
    update_cache: no
  when: ansible_distribution_release == "xenial"
  tags: netq

- name: Add Cumulus Repo for Cumulus Linux
  apt_repository:
    repo: deb https://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.2
    state: present
    update_cache: no
  when: ansible_distribution == "Debian"
  tags: netq

- name: Upgrade NetQ to 1.2.1
  apt:
    name: cumulus-netq
    state: latest
    update_cache: yes
  tags: netq

- name: Check if netq is already configured
  command: netq config show server json
  register: netq_config
  tags: netq

- name: Add netq server IP
  command: netq config add server {{netq_ts}} {{ nodes[ansible_hostname]["interfaces"]["mgmt"]["eth0"]["vrf"] }}
  tags: netq
  when: netq_config.stdout == ""

- name: Restart Rsyslog
  service:
    name: rsyslog
    state: restarted
  when: netq_config.stdout == ""
  tags: netq

- name: Restart NetQ Agent
  command: netq config restart agent
  tags: netq
  when: netq_config.stdout == ""

