---
# Ping script is so servers generate traffic to populate MAC tables
- name: Configure Server01 Ping Cronjob
  cron:
    name: "server ping"
    job: "ping 192.168.1.1"
  become: yes
  become_user: cumulus


- name: Configure Server02 Ping Cronjob
  cron:
    name: "server ping"
    job: "ping 192.168.1.2"
  become: yes
  become_user: cumulus
