---
# The frr daemons file is a static file that specifies which subdaemons
# are actually running (zebra, bgpd, ospf).
- name: configure frr daemons file
  copy:
    src: daemons
    dest: /etc/frr/daemons
  notify:
    - restart frr

# This writes configuration to the frr configuration file using the
# information in group_vars/all. The biggest difference between spine and
# leaf configuration are the prefix lists - leafs should only advertise their
# neighboring networks, but spines should advertise any networks they accept.
- name: configure frr configuration
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    validate: vtysh -C -f %s
  notify:
    - reload frr
