---
# This command actually restarts frr. This command will actually drop all
# routes currently in progress, so this will interrupt networking currently in
# place.
- name: restart frr
  service:
    name: frr
    state: restarted

# This command reloads frr config.
- name: reload frr
  service:
    name: frr
    state: reloaded
